GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbnRpQG1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQwNDA2MDgxLCJleHAiOjE3NDA0OTI0ODF9.BcCgLerko-WaP8fwZYAFBqsXIEUxSWpvBT-90vCNLp0

