POST http://localhost:3000/todos/resetdb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbnRpQG1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQwMTAxMzk0LCJleHAiOjE3NDAxODc3OTR9.RLmQ2YIPVypiXj7qyD0lPP9B5H4w5ieH8Mco7Bvjrzs

